[workspace]
resolver = "2"
members = ["crates/kevala", "crates/kevala-cli", "crates/kevala-wasm"]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/bvolpato/kevala"
rust-version = "1.85"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false

[profile.release-wasm]
inherits = "release"
opt-level = 3
strip = true

[profile.test]
opt-level = 3
